using System;
using System.Collections.Generic;
using System.Text;

namespace TailwindUSS.Editor
{
    /// <summary>
    /// Represents the uss emitter.
    /// </summary>
    internal sealed class UssEmitter
    {
        /// <summary>
        /// Emits USS output from resolved utility tokens.
        /// </summary>
        public string Emit(IEnumerable<ResolvedUtility> utilities)
        {
            var builder = new StringBuilder();
            builder.AppendLine("/* Generated by TailwindUSS. */");
            builder.AppendLine("/* Do not edit manually. */");
            builder.AppendLine();

            var sorted = new List<ResolvedUtility>(utilities);
            sorted.Sort((left, right) => string.CompareOrdinal(GetSelector(left), GetSelector(right)));

            for (var i = 0; i < sorted.Count; i++)
            {
                var utility = sorted[i];
                builder.Append(GetSelector(utility)).AppendLine(" {");

                foreach (var declaration in utility.Declarations)
                {
                    builder.Append("    ")
                        .Append(declaration.PropertyName)
                        .Append(": ")
                        .Append(declaration.Value)
                        .AppendLine(";");
                }

                builder.AppendLine("}");
                if (i < sorted.Count - 1)
                {
                    builder.AppendLine();
                }
            }

            return builder.ToString();
        }

        /// <summary>
        /// Escapes special characters in a class name for USS selector compatibility.
        /// </summary>
        internal static string EscapeClassName(string className)
        {
            var builder = new StringBuilder(className.Length);
            foreach (var character in className)
            {
                if (char.IsLetterOrDigit(character) || character == '-' || character == '_')
                {
                    builder.Append(character);
                }
                else
                {
                    builder.Append('\\').Append(character);
                }
            }

            return builder.ToString();
        }

        /// <summary>
        /// Builds a selector from class names with an optional selector suffix.
        /// </summary>
        internal static string BuildSelector(IEnumerable<string> classNames, string selectorSuffix = "")
        {
            var builder = new StringBuilder();
            foreach (var className in classNames)
            {
                builder.Append('.').Append(EscapeClassName(className));
            }

            builder.Append(selectorSuffix);
            return builder.ToString();
        }

        private static string GetSelector(ResolvedUtility utility)
        {
            if (!string.IsNullOrEmpty(utility.SelectorOverride))
            {
                return utility.SelectorOverride;
            }

            return BuildSelector(new[] { utility.Token }, utility.SelectorSuffix);
        }
    }
}
