namespace TailwindUSS.Editor.Tests
{
    public sealed class UssEmitterTests
    {
        [Test]
        public void Emit_SortsUtilitiesAndFormatsDeclarations()
        {
            var emitter = new UssEmitter();
            var utilities = new[]
            {
                new ResolvedUtility("text-white", new[] { new StyleDeclaration("color", "#FFFFFF") }),
                new ResolvedUtility("bg-blue-500", new[] { new StyleDeclaration("background-color", "#3B82F6") }),
                new ResolvedUtility("px-4", new[]
                {
                    new StyleDeclaration("padding-left", "16px"),
                    new StyleDeclaration("padding-right", "16px")
                })
            };

            var output = emitter.Emit(utilities);

            const string expected = "/* Generated by TailwindUSS. */\n/* Do not edit manually. */\n\n.bg-blue-500 {\n    background-color: #3B82F6;\n}\n\n.px-4 {\n    padding-left: 16px;\n    padding-right: 16px;\n}\n\n.text-white {\n    color: #FFFFFF;\n}\n";
            Assert.That(output.Replace("\r\n", "\n"), Is.EqualTo(expected));
        }

        [Test]
        public void Emit_AppendsSelectorSuffixWhenProvided()
        {
            var emitter = new UssEmitter();
            var utilities = new[]
            {
                new ResolvedUtility("example", new[]
                {
                    new StyleDeclaration("display", "flex")
                }, ":hover")
            };

            var output = emitter.Emit(utilities);

            Assert.That(output.Replace("\r\n", "\n"), Does.Contain(".example:hover {\n    display: flex;\n}"));
        }

        [Test]
        public void Emit_EscapesVariantClassNamesBeforeAppendingSelectorSuffix()
        {
            var emitter = new UssEmitter();
            var utilities = new[]
            {
                new ResolvedUtility("hover:bg-blue-500", new[]
                {
                    new StyleDeclaration("background-color", "#3B82F6")
                }, ":hover")
            };

            var output = emitter.Emit(utilities);

            Assert.That(output.Replace("\r\n", "\n"), Does.Contain(".hover\\:bg-blue-500:hover {\n    background-color: #3B82F6;\n}"));
        }
    }
}
