using System;
using System.Collections.Generic;
using System.Text;

namespace TailwindUSS.Editor
{
    internal sealed class UssEmitter
    {
        public string Emit(IEnumerable<ResolvedUtility> utilities)
        {
            var builder = new StringBuilder();
            builder.AppendLine("/* Generated by TailwindUSS. */");
            builder.AppendLine("/* Do not edit manually. */");
            builder.AppendLine();

            var sorted = new List<ResolvedUtility>(utilities);
            sorted.Sort((left, right) => string.CompareOrdinal(left.Token, right.Token));

            for (var i = 0; i < sorted.Count; i++)
            {
                var utility = sorted[i];
                builder.Append('.').Append(EscapeClassName(utility.Token)).Append(utility.SelectorSuffix).AppendLine(" {");

                foreach (var declaration in utility.Declarations)
                {
                    builder.Append("    ")
                        .Append(declaration.PropertyName)
                        .Append(": ")
                        .Append(declaration.Value)
                        .AppendLine(";");
                }

                builder.AppendLine("}");
                if (i < sorted.Count - 1)
                {
                    builder.AppendLine();
                }
            }

            return builder.ToString();
        }

        private static string EscapeClassName(string className)
        {
            var builder = new StringBuilder(className.Length);
            foreach (var character in className)
            {
                if (char.IsLetterOrDigit(character) || character == '-' || character == '_')
                {
                    builder.Append(character);
                }
                else
                {
                    builder.Append('\\').Append(character);
                }
            }

            return builder.ToString();
        }
    }
}
